# 第31章习题

## 1、说出异常处理的3个优点

错误处理、事件通知、特殊情况处理、终止行为、非常规控制流程

## 2、如果你不想做任何特殊的事情来处理异常，那么异常会发生什么

出现特殊情况后，会触发异常，使用 Python 默认的异常处理器处理后，终止程序

## 3、如何从一个异常中恢复你的脚本

使用 `try/except` 语句捕获并处理异常，后续程序会继续运行

## 4、说出在脚本中触发异常的两个方式

`raise` 和 `assert`

## 5、指出两种方式，不管异常是否发生，用来指定最终运行的行为

`try/finally` 和 `with/as`
